name: Build and Deploy to krystianslowik.com
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install Dependencies and Build
        run: |
          npm install  
          REACT_APP_OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} CI=false npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ vars.PORT }} krystianslowik.com >> ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
          REMOTE_PATH: ${{ vars.REMOTE_PATH }}
          USERNAME: ${{ vars.USERNAME }}
          PORT: ${{ vars.PORT }}
        run: |
          rsync -avz --delete -e 'ssh -o StrictHostKeyChecking=no -p $PORT' build/ $USERNAME@krystianslowik.com:$REMOTE_PATH
